### ISSUE TITLE
cannot install KMNIr

### ISSUE THREAD

**Issue by fritsander** [bvhest/KNMIr#1]
Hi,

KMNIr does not want to install. When running:
devtools::install_github("hestbv/KNMIr")
I get the following message:
> devtools::install_github("hestbv/KNMIr")
Downloading GitHub repo hestbv/KNMIr@master
from URL https://api.github.com/repos/hestbv/KNMIr/zipball/master
Installation failed: Not Found (404)
Please help.

Thanks in advance.

Fritsander

**Comment by bvhest** [comment]
Please use the following for installation (note the difference in the first part of the url):
devtools::install_github("bvhest/KNMIr")
